project_name: grade

release:
  github:
    owner: sv-go-tools
    name: grade

builds:
  - binary: grade
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    main: ./
    ldflags: -s -w -X main.version={{ .Tag }}

archives:
  - format: tar.gz
    wrap_in_directory: false
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}-{{ .Tag }}-checksums.txt"

dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - grade
    image_templates:
      - "docker.pkg.github.com/sv-go-tools/{{ .ProjectName }}/{{ .ProjectName }}:latest"
      - "docker.pkg.github.com/sv-go-tools/{{ .ProjectName }}/{{ .ProjectName }}:{{ .Tag }}"
      - "docker.pkg.github.com/sv-go-tools/{{ .ProjectName }}/{{ .ProjectName }}:v{{ .Major }}"
