name: Test Master Branch
on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Checkout code
        uses: actions/checkout@v1
      - name: unittests
        run: go test -race -cover -coverprofile=coverage.txt -covermode=atomic -cpu 1,2 -bench . -benchmem ./... > test.log
      - name: Show log
        if: always()
        run: cat test.log
      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Mongo
        run: >-
          go run . mongo
          --connection-url="mongodb://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PASSWORD }}@bench-shard-00-00-jhj17.mongodb.net:27017,bench-shard-00-01-jhj17.mongodb.net:27017,bench-shard-00-02-jhj17.mongodb.net:27017/test?ssl=true&replicaSet=bench-shard-0&authSource=admin&retryWrites=true&w=majority"
          --database="sv-go-tools"
          --collection="grade"
          --tag "hardwareID=github/actions"
          --tag "goVersion=$(go version | cut -d' ' -f3-)"
          --tag "revision=${{ github.sha }}"
          < test.log
